version: "3"

tasks:
  default:
    silent: false
    cmds: ["task -l"]

  build:
    desc: Build a container
    requires:
      vars:
        - dir
    vars:
      platform: '{{ .platform | default "linux/arm64" }}'
    cmds:
      - docker buildx build --pull --platform {{ .platform }} {{ .dir }}

  version:all:
    desc: Run versioning for all containers
    silent: true
    cmds:
      - ./hack/version_all.sh

  version:
    desc: Version the packages
    env:
      GIT_CLIFF__BUMP__INITIAL_TAG: "{{ .dir }}-1.0.0"
    requires:
      vars:
        - dir
    cmds:
      - ./hack/version.sh {{ .dir }}

  changelog:
    desc: Generate the changelog
    env:
      GIT_CLIFF__BUMP__INITIAL_TAG: "{{ .dir }}-1.0.0"
    requires:
      vars:
        - dir
    cmds:
      - |
        dir="{{ .dir }}"
        sanitised=$(echo $dir | tr '/' '-')
        git cliff --include-path "$dir/*" --tag-pattern "$sanitised.*" --bump >"$dir/CHANGELOG.md"

  new:
    desc: Create a new container
    requires:
      vars:
        - dir
    cmds:
      - mkdir -p "{{ .dir }}"
      - touch "{{ .dir }}/Dockerfile"
