name: Build

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      containers: ${{ steps.check.outputs.containers }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: go-task/setup-task@v2
      - name: Install git-cliff
        uses: taiki-e/install-action@git-cliff
      - name: Version container
        id: check
        run: |
          CONTAINERS=()

          for dir in toolkit kubectl pipelines k6/statsd k6/disruptor; do
            result=$(task version dir="$dir")
            echo "[$dir]: $result"
            if [ "$result" != "skip" ]; then
              entry=$(echo "$result" | jq -c --arg dir "$dir" '. + {dir: $dir}')
              CONTAINERS+=("$entry")
              git add "$dir/CHANGELOG.md"
            fi
          done

          echo "containers=[$(
            IFS=,
            echo "${CONTAINERS[*]}"
          )]" >> "$GITHUB_OUTPUT"
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore(docs): update changelogs"

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    needs: [version]
    if: needs.version.outputs.containers != '[]'
    strategy:
      matrix:
        include: ${{ fromJson(needs.version.outputs.containers) }}
    steps:
      - uses: actions/checkout@v6
      - name: Tag new version
        run: |
          git tag ${{ matrix.tag }}
          git push origin ${{ matrix.tag }}
      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v4
      - uses: docker/setup-buildx-action@v4
      - uses: docker/build-push-action@v7
        with:
          platforms: linux/amd64,linux/arm64
          context: ${{ matrix.dir }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.dir }}:latest
            ghcr.io/${{ github.repository }}/${{ matrix.dir }}:${{ matrix.version }}
