name: Build

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      containers: ${{ steps.check.outputs.containers }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0
          ref: main
      - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4
        with:
          install: true
          cache: true
      - name: Version container
        id: check
        run: |
          CONTAINERS=()

          for dir in *; do
            if [[ ! -d "$dir" ]]; then
              continue
            fi
            if [[ ! -f "$dir/Dockerfile" ]]; then
              continue
            fi
            output=$(task version dir="$dir")
            echo "[$dir]: $output"
            if [[ $(echo "$output" | jq -r '.skip') != "true" ]]; then
              entry=$(echo "$output" | jq -c --arg dir "$dir" '. + {dir: $dir}')
              CONTAINERS+=("$entry")
              echo "$output" | jq -r '.changelog' > "$dir/CHANGELOG.md"
              git add "$dir/CHANGELOG.md"
              tag=$(echo "$output" | jq -r '.tag')
              git tag "$tag"
              git push origin "$tag"
            fi
          done

          echo "containers=[$(
            IFS=,
            echo "${CONTAINERS[*]}"
          )]" >> "$GITHUB_OUTPUT"
      - uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7
        with:
          commit_message: "chore(docs): update changelogs"

  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs: [version]
    if: needs.version.outputs.containers != '[]'
    strategy:
      matrix:
        include: ${{ fromJson(needs.version.outputs.containers) }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          ref: main
      - uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4
      - uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4
      - uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
        with:
          platforms: linux/amd64,linux/arm64
          context: ${{ matrix.dir }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.dir }}:latest
            ghcr.io/${{ github.repository }}/${{ matrix.dir }}:${{ matrix.version }}
